# One-time generator for mission specs — run from GAME/MISSIONS/
$missions = @(
  @{ n="01"; id="M01_LOADING"; title="Loading Screen"; arc="Arc 1 — The Summoning"; ms="Chapter-01-Loading-Screen.md"; zones="starting-meadow, castle-lumora"; time="15–20 min"; pre="None"; q="q_awaken"; narr="Haruto summoned as Eternal Player; System establishes tone."; game="Complete summon UI; wake in meadow; bind gauntlet."; start="New game."; end="Gauntlet bound; M02 unlocked."; fail="N/A (tutorial)"; scenes="S0101–S0105"; chars="Haruto, System, Seraphina, Luminara, Velvet"; objs="crystal_gauntlet, quest_log, loading UI"; bond="—"; faction="—"; rewards="Crystal Gauntlet, Quest log"; unlocks="M02"; flags=""; branch=""; impl="Godot: intro cutscene + meadow spawn" },
  @{ n="02"; id="M02_PARTY_SELECT"; title="Starter Party Selection"; arc="Arc 1"; ms="Chapter-02-Starter-Party-Selection.md"; zones="castle-lumora, golden-tankard"; time="20–25 min"; pre="M01"; q="—"; narr="Haruto forced to pick party; factions claim him."; game="Party selection UI; survive Veil break-in."; start="M01 complete."; end="Party roster locked; SD7 quest active."; fail="N/A"; scenes="S0201–S0206"; chars="Full starter cast"; objs="starter_party_window, romance_flag_popup"; bond="+1 all starters"; faction="Radiant/Veil baseline"; rewards="Party roster, jealousy meter"; unlocks="M03"; flags=""; branch="Party composition affects banter"; impl="Dialog tree + combat intro" },
  @{ n="03"; id="M03_WALK_SD7"; title="Walk to Sky Dungeon 7"; arc="Arc 1"; ms="Chapter-03-The-Walk-to-Sky-Dungeon-7.md"; zones="travel-road-sd7"; time="15 min"; pre="M02"; q="q_gate"; narr="Travel banter; mixed-faction friction."; game="Escort segment; optional scout fight."; start="Left castle."; end="Dungeon approach reachable."; fail="Party wipe → respawn"; scenes="S0301–S0304"; chars="Party"; objs="—"; bond="+1 if no jealousy spike"; faction="—"; rewards="Travel XP"; unlocks="M04"; flags=""; branch="Skip combat loses XP"; impl="Zone transition to forest-ruin-gate" },
  @{ n="04"; id="M04_TUTORIAL_LIAR"; title="Tutorial Dungeon (Liar)"; arc="Arc 1"; ms="Chapter-04-Tutorial-Dungeon-Liar.md"; zones="sd7-tutorial"; time="20 min"; pre="M03"; q="—"; narr="Dungeon language; System not benevolent."; game="Clear tutorial floor; tile puzzles."; start="Enter sd7-tutorial."; end="Floor clear."; fail="Trap death → respawn"; scenes="S0401–S0404"; chars="Party"; objs="tile_set, unity_tile"; bond="—"; faction="—"; rewards="Tutorial loot, trap codex"; unlocks="M05"; flags=""; branch=""; impl="Tile puzzle prototype" },
  @{ n="05"; id="M05_SUNNY_HATES"; title="The Helpful Tutorial That Hates You"; arc="Arc 1"; ms="Chapter-05-The-Helpful-Tutorial-That-Hates-You.md"; zones="sd7-tutorial"; time="20 min"; pre="M04"; q="—"; narr="Sunny weaponizes help."; game="Follow/ignore Sunny; survive traps."; start="Sunny appears."; end="Sunny entity registered."; fail="Trap wave wipe"; scenes="S0501–S0504"; chars="Sunny, Haruto, Party"; objs="sunny overlay, trap_sunny_tip"; bond="—"; faction="—"; rewards="Sunny system, debuff immunity x1"; unlocks="M06"; flags=""; branch="Follow tips = harder path"; impl="SunnyControl node" },
  @{ n="06"; id="M06_VEIL_KEY"; title="The Veil Key Problem"; arc="Arc 1"; ms="Chapter-06-The-Veil-Key-Problem.md"; zones="sd7-upper"; time="25 min"; pre="M05"; q="—"; narr="Radiant+Veil cooperation required."; game="Obtain seal + key; co-op door."; start="Upper dungeon."; end="Keys party-held; co-op gate cleared."; fail="Gate shock damage"; scenes="S0601–S0604"; chars="Seraphina, Bone Commander, Haruto"; objs="radiant_seal, veil_curse_key, coop_gate"; bond="+1 Seraphina/Bone"; faction="party_holds_keys"; rewards="Veil Key pair"; unlocks="M07"; flags="refused_radiant_ownership, refused_veil_contract"; branch="Refuse ownership dialogue"; impl="Dual interact gate" }
)

# Additional missions 07-35 - writing full file via expanded script below
