#!/usr/bin/env python3
"""
Ollama Book Generator
A Python script to generate books using Ollama AI models
"""

import ollama
import os
import json
from datetime import datetime
from typing import List, Dict, Any

def generate_chapter(prompt: str, model: str = "llama3.1") -> str:
    """Generate a chapter using Ollama"""
    try:
        response = ollama.generate(model=model, prompt=prompt)
        return response['response']
    except Exception as e:
        print(f"Error generating chapter: {e}")
        return f"Error: Could not generate chapter. {str(e)}"

def create_book(title: str, genre: str, characters: List[str], setting: str, 
                plot_points: List[str], output_file: str = "story.txt", 
                model: str = "llama3.1") -> str:
    """Create a complete book with multiple chapters"""
    
    print(f"📚 Creating book: {title}")
    print(f"🎭 Genre: {genre}")
    print(f"📍 Setting: {setting}")
    print(f"👥 Characters: {', '.join(characters)}")
    print(f"📖 Plot points: {len(plot_points)}")
    print("-" * 50)
    
    # Initialize story structure
    story = f"# {title}\n\n"
    story += f"**Genre:** {genre}\n"
    story += f"**Setting:** {setting}\n"
    story += f"**Characters:** {', '.join(characters)}\n"
    story += f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
    story += "---\n\n"
    
    # Introduction chapter
    print("📝 Generating Chapter 1: The Beginning...")
    intro_prompt = f"""Write an engaging opening chapter for a {genre} story set in {setting}. 
    Introduce {', '.join(characters)} and hint at {plot_points[0]}. 
    Use vivid details, create atmosphere, and establish the tone. Aim for approximately 500 words.
    Make it compelling and draw the reader in."""
    
    intro_content = generate_chapter(intro_prompt, model)
    story += "## Chapter 1: The Beginning\n\n" + intro_content + "\n\n"
    
    # Middle chapters
    for i, plot_point in enumerate(plot_points[1:-1], 2):
        print(f"📝 Generating Chapter {i}...")
        chapter_prompt = f"""Write chapter {i} for a {genre} story in {setting}. 
        Focus on {characters[0]} navigating {plot_point}. 
        Include dialogue, action, and character development. 
        Build tension and advance the plot. Aim for approximately 600 words."""
        
        chapter_content = generate_chapter(chapter_prompt, model)
        story += f"## Chapter {i}\n\n" + chapter_content + "\n\n"
    
    # Final chapter
    print(f"📝 Generating Chapter {len(plot_points)}: The End...")
    final_prompt = f"""Write the final chapter for a {genre} story in {setting}. 
    Resolve {plot_points[-1]} with {', '.join(characters)}. 
    Provide a satisfying conclusion to the story. 
    Tie up loose ends and give the characters a proper resolution. Aim for approximately 700 words."""
    
    final_content = generate_chapter(final_prompt, model)
    story += f"## Chapter {len(plot_points)}: The End\n\n" + final_content + "\n\n"
    
    # Add metadata
    story += "---\n\n"
    story += f"*Generated by Ollama Book Generator on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n"
    story += f"*Model used: {model}*\n"
    
    # Save to file
    try:
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(story)
        
        # Also save as JSON for programmatic access
        json_file = output_file.replace('.txt', '.json')
        book_data = {
            "title": title,
            "genre": genre,
            "characters": characters,
            "setting": setting,
            "plot_points": plot_points,
            "chapters": [
                {"title": "Chapter 1: The Beginning", "content": intro_content},
                *[{"title": f"Chapter {i}", "content": generate_chapter(f"Write chapter {i} for a {genre} story in {setting}. Focus on {characters[0]} navigating {plot_points[i-1]}. Include dialogue, action, and character development. Aim for approximately 600 words.", model)} for i in range(2, len(plot_points))],
                {"title": f"Chapter {len(plot_points)}: The End", "content": final_content}
            ],
            "generated_at": datetime.now().isoformat(),
            "model": model
        }
        
        with open(json_file, 'w', encoding='utf-8') as f:
            json.dump(book_data, f, indent=2, ensure_ascii=False)
        
        return f"✅ Book saved as {output_file} and {json_file}"
        
    except Exception as e:
        return f"❌ Error saving book: {str(e)}"

def generate_character_profile(name: str, role: str, genre: str, model: str = "llama3.1") -> str:
    """Generate a detailed character profile"""
    prompt = f"""Create a detailed character profile for {name}, a {role} in a {genre} story. 
    Include their background, personality traits, motivations, fears, strengths, weaknesses, 
    and key relationships. Make them compelling and three-dimensional. 
    Aim for approximately 300 words."""
    
    return generate_chapter(prompt, model)

def generate_plot_ideas(genre: str, setting: str, num_ideas: int = 5, model: str = "llama3.1") -> List[str]:
    """Generate multiple plot ideas for a story"""
    prompt = f"""Generate {num_ideas} creative plot ideas for a {genre} story set in {setting}. 
    Each idea should be a brief but engaging plot point or conflict. 
    Make them diverse and interesting. Return each idea on a new line."""
    
    response = generate_chapter(prompt, model)
    return [idea.strip() for idea in response.split('\n') if idea.strip()]

def main():
    """Main function with example usage"""
    print("🚀 Ollama Book Generator")
    print("=" * 50)
    
    # Check if Ollama is available
    try:
        models = ollama.list()
        print(f"📋 Available models: {[model['name'] for model in models['models']]}")
    except Exception as e:
        print(f"❌ Error connecting to Ollama: {e}")
        print("Make sure Ollama is running: ollama serve")
        return
    
    # Example book configuration
    title = "The Moon Runners"
    genre = "Science Fiction"
    characters = ["Lila, a skilled co-pilot", "You, a robotics expert"]
    setting = "Satellite City Station, 2056 post-glacial melt"
    plot_points = [
        "a mysterious lunar race invitation",
        "a dangerous sabotage during the Moon Runners race", 
        "uncovering a faster-than-light travel secret",
        "winning lunar land and a new future"
    ]
    output_file = "moon_runners_story.txt"
    
    # Generate the book
    result = create_book(title, genre, characters, setting, plot_points, output_file)
    print(result)
    
    # Generate additional content
    print("\n" + "=" * 50)
    print("🎭 Generating character profiles...")
    
    for character in characters:
        name, role = character.split(", ")
        print(f"\n👤 {name}:")
        profile = generate_character_profile(name, role, genre)
        print(profile[:200] + "..." if len(profile) > 200 else profile)
    
    print("\n" + "=" * 50)
    print("💡 Generating additional plot ideas...")
    plot_ideas = generate_plot_ideas(genre, setting, 3)
    for i, idea in enumerate(plot_ideas, 1):
        print(f"{i}. {idea}")

if __name__ == "__main__":
    main()
